name: macos

on:
<<<<<<< HEAD
=======
  push:
    branches: [ main ]
>>>>>>> 5da26c2 (Add macos build process)
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - build_type: debug
            lto: "n"
          - build_type: release
            lto: "n"
          - build_type: release
            lto: "y"

<<<<<<< HEAD
    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macos-${{ matrix.build_type }}-${{ matrix.lto }}
      cancel-in-progress: true

=======
>>>>>>> 5da26c2 (Add macos build process)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
<<<<<<< HEAD
          xmake-version: '2.9.9'
=======
          xmake-version: branch@master
>>>>>>> 5da26c2 (Add macos build process)
          actions-cache-folder: '.xmake-cache'

      - name: Package
        run: |
          xmake config --yes --verbose --toolchain=clang --mode=${{ matrix.build_type }} --policies=build.optimization.lto:${{ matrix.lto }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
<<<<<<< HEAD
          name: macos-${{ matrix.build_type }}-lto_${{ matrix.lto }}.tar.xz
=======
          name: linux-${{ matrix.build_type }}-lto_${{ matrix.lto }}.tar.xz
>>>>>>> 5da26c2 (Add macos build process)
          path: build/package/*
          compression-level: 0
          if-no-files-found: error
