name: windows

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        include:
          - build_type: release
            runtimes: MD
            lto: "n"
          - build_type: release
            runtimes: MT
            lto: "y"

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-windows-${{ matrix.build_type }}-${{ matrix.lto }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.9.9'
          actions-cache-folder: '.xmake-cache'

      - name: Package
        run: |
          xmake config --yes --verbose --runtimes=${{ matrix.runtimes }} --policies=build.optimization.lto:${{ matrix.lto }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.build_type }}-${{ matrix.runtimes }}-lto_${{ matrix.lto }}.7z
          path: build/package/*
          compression-level: 0
          if-no-files-found: error
